name: flow_lyrix
description: A new Flutter project.
publish_to: 'none'
version: 0.4.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  receive_sharing_intent:
    git:
      url: https://github.com/AyushmanG26/receive_sharing_intent.git
      ref: abedc3d6d5b80df396e9c300fd1a052cbab08827

  christian_lyrics:
    git:
      url: https://github.com/Movinghead333/christian_lyrics.git
      ref: 57e4caccc570e9980d82c45a4309180523b3ca6c

  
  # christian_lyrics:
  #   path: C:/Dev/flutter_projects/forks/christian_lyrics
  
  sylt_parser:
    git:
      url: https://github.com/Movinghead333/sylt_parser.git
      ref: 20fdd555dbce83241f4bb0c81049ac93db79f49e

  # sylt_parser:
  #   path: C:/Dev/dart_projects/sylt_parser

  uri_to_file: ^1.0.0

  # Use for provider based app-state management
  provider: ^6.0.5

  # Used for BehaviourSubjects
  rxdart: ^0.27.7

  audio_session: ^0.1.18
  audio_service: ^0.18.12
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
